-- Expand the shared ingredient catalog so recipes can be built from real pantries.
--
-- Data only: no schema, function, policy, or grant changes.
--
-- Conventions enforced by the existing constraints and validate_mvp_row():
--   * base_unit is 'ml' for liquids, 'each' only where a weight is meaningless,
--     and 'g' for everything else. It is never changed for an existing slug.
--   * every 'ml' row carries density_g_per_ml and every 'each' row carries
--     average_unit_weight_g, because record_waste() converts through them.
--   * countable produce stays 'g' and carries average_unit_weight_g per piece.
--   * dietary_tags is limited to 'vegan' and 'vegetarian'; vegan implies vegetarian.
--   * allergens are drawn from the EU 14, spelled as the original rows spell them.

set statement_timeout = '60s';

insert into public.ingredients (
  slug,
  name,
  base_unit,
  dietary_tags,
  allergens,
  recommended_storage_location,
  typical_shelf_life_days,
  storage_instructions,
  density_g_per_ml,
  average_unit_weight_g
) values
  -- Original catalog rows, restated so the conflict clause backfills their
  -- missing density and per-piece weights. base_unit is unchanged.
  ('tomato', 'Tomato', 'g', array['vegan', 'vegetarian'], '{}', 'counter', 7, 'Keep away from direct sunlight; refrigerate once fully ripe if needed.', null, 120),
  ('onion', 'Onion', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 30, 'Store in a cool, dry, ventilated place.', null, 110),
  ('garlic', 'Garlic', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 60, 'Keep whole bulbs dry and ventilated.', null, 4),
  ('rice', 'Rice', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('pasta', 'Pasta', 'g', array['vegetarian'], array['gluten'], 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('potato', 'Potato', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 21, 'Keep cool, dark, dry, and away from onions.', null, 170),
  ('carrot', 'Carrot', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 21, 'Refrigerate dry in a ventilated bag.', null, 70),
  ('broccoli', 'Broccoli', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 5, 'Refrigerate unwashed in a loose bag.', null, 300),
  ('spinach', 'Spinach', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 5, 'Refrigerate dry with an absorbent towel.', null, null),
  ('chickpeas', 'Chickpeas', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store dry or canned chickpeas according to package guidance.', null, null),
  ('lentils', 'Lentils', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('tofu', 'Tofu', 'g', array['vegan', 'vegetarian'], array['soybeans'], 'refrigerator', 7, 'Keep refrigerated and use promptly after opening.', null, 300),
  ('chicken-breast', 'Chicken breast', 'g', '{}', '{}', 'refrigerator', 2, 'Keep refrigerated and separate from ready-to-eat food.', null, 175),
  ('salmon', 'Salmon', 'g', '{}', array['fish'], 'refrigerator', 2, 'Keep refrigerated and use promptly.', null, 150),
  ('egg', 'Egg', 'each', array['vegetarian'], array['eggs'], 'refrigerator', 28, 'Keep refrigerated in the original carton.', null, 60),
  ('milk', 'Milk', 'ml', array['vegetarian'], array['milk'], 'refrigerator', 7, 'Keep refrigerated and follow the package date.', 1.03, null),
  ('yogurt', 'Yogurt', 'g', array['vegetarian'], array['milk'], 'refrigerator', 10, 'Keep refrigerated and sealed.', null, null),
  ('cheese', 'Cheese', 'g', array['vegetarian'], array['milk'], 'refrigerator', 14, 'Wrap and refrigerate after opening.', null, null),
  ('bread', 'Bread', 'g', array['vegetarian'], array['gluten'], 'counter', 5, 'Keep sealed or freeze portions.', null, 35),
  ('olive-oil', 'Olive oil', 'ml', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store sealed away from heat and light.', 0.91, null),

  -- Seasoning and baking staples.
  ('salt', 'Salt', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 3650, 'Store dry in a sealed container.', null, null),
  ('sea-salt-flakes', 'Sea salt flakes', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 3650, 'Store dry in a sealed container.', null, null),
  ('black-pepper', 'Ground black pepper', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('white-pepper', 'Ground white pepper', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('peppercorns', 'Black peppercorns', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 1095, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('sugar', 'White sugar', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 1095, 'Store dry in a sealed container.', null, null),
  ('brown-sugar', 'Brown sugar', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Store dry in a sealed container to keep it soft.', null, null),
  ('icing-sugar', 'Icing sugar', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Store dry in a sealed container.', null, null),
  ('flour', 'Wheat flour', 'g', array['vegan', 'vegetarian'], array['gluten'], 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('bread-flour', 'Bread flour', 'g', array['vegan', 'vegetarian'], array['gluten'], 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('whole-wheat-flour', 'Whole wheat flour', 'g', array['vegan', 'vegetarian'], array['gluten'], 'pantry', 270, 'Store dry in a sealed container; refrigerate in warm weather.', null, null),
  ('cornstarch', 'Cornstarch', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Store dry in a sealed container.', null, null),
  ('baking-powder', 'Baking powder', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 540, 'Keep sealed and dry; moisture ruins the rise.', null, null),
  ('baking-soda', 'Baking soda', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 1095, 'Store dry in a sealed container.', null, null),
  ('dry-yeast', 'Dry yeast', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Keep sealed and dry; refrigerate after opening.', null, null),
  ('vanilla-extract', 'Vanilla extract', 'ml', array['vegan', 'vegetarian'], '{}', 'pantry', 1095, 'Store sealed away from heat and light.', 0.88, null),
  ('cocoa-powder', 'Cocoa powder', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('dark-chocolate', 'Dark chocolate', 'g', array['vegan', 'vegetarian'], array['soybeans'], 'pantry', 365, 'Store cool and dry away from strong odours.', null, null),
  ('gelatine', 'Gelatine', 'g', '{}', '{}', 'pantry', 1095, 'Store dry in a sealed container.', null, null),
  ('polenta', 'Polenta', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('breadcrumbs', 'Breadcrumbs', 'g', array['vegan', 'vegetarian'], array['gluten'], 'pantry', 180, 'Store dry in a sealed container.', null, null),
  ('panko-breadcrumbs', 'Panko breadcrumbs', 'g', array['vegan', 'vegetarian'], array['gluten'], 'pantry', 180, 'Store dry in a sealed container.', null, null),
  ('honey', 'Honey', 'g', array['vegetarian'], '{}', 'pantry', 1095, 'Store sealed at room temperature; crystallisation is harmless.', 1.42, null),
  ('maple-syrup', 'Maple syrup', 'ml', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Refrigerate after opening.', 1.33, null),
  ('nutritional-yeast', 'Nutritional yeast', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 540, 'Store dry in a sealed container.', null, null),

  -- Dried herbs and spices.
  ('dried-basil', 'Dried basil', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('dried-oregano', 'Dried oregano', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('dried-thyme', 'Dried thyme', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('dried-rosemary', 'Dried rosemary', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('dried-dill', 'Dried dill', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('bay-leaves', 'Bay leaves', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('italian-herbs', 'Italian herb mix', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('herbes-de-provence', 'Herbes de Provence', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('sweet-paprika', 'Sweet paprika', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('smoked-paprika', 'Smoked paprika', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('chilli-flakes', 'Chilli flakes', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('chilli-powder', 'Chilli powder', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('cayenne-pepper', 'Cayenne pepper', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('ground-cumin', 'Ground cumin', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('cumin-seeds', 'Cumin seeds', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 1095, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('ground-coriander', 'Ground coriander', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('coriander-seeds', 'Coriander seeds', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 1095, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('ground-turmeric', 'Ground turmeric', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('ground-ginger', 'Ground ginger', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('garam-masala', 'Garam masala', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('curry-powder', 'Curry powder', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('ras-el-hanout', 'Ras el hanout', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('zaatar', 'Zaatar', 'g', array['vegan', 'vegetarian'], array['sesame'], 'pantry', 540, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('chinese-five-spice', 'Chinese five spice', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('ground-cinnamon', 'Ground cinnamon', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('cinnamon-stick', 'Cinnamon stick', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 1095, 'Keep sealed in a cool, dark cupboard.', null, 3),
  ('ground-nutmeg', 'Ground nutmeg', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('ground-cloves', 'Ground cloves', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('cardamom-pods', 'Cardamom pods', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 1095, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('star-anise', 'Star anise', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 1095, 'Keep sealed in a cool, dark cupboard.', null, 2),
  ('saffron', 'Saffron', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard away from light.', null, null),
  ('allspice', 'Ground allspice', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('sumac', 'Sumac', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('fennel-seeds', 'Fennel seeds', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 1095, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('caraway-seeds', 'Caraway seeds', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 1095, 'Keep sealed in a cool, dark cupboard.', null, null),
  ('mustard-seeds', 'Mustard seeds', 'g', array['vegan', 'vegetarian'], array['mustard'], 'pantry', 1095, 'Keep sealed in a cool, dark cupboard.', null, null),

  -- Fresh herbs and aromatics.
  ('fresh-basil', 'Fresh basil', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 5, 'Keep the stems in water and avoid the coldest shelf.', null, null),
  ('fresh-parsley', 'Fresh parsley', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 7, 'Refrigerate wrapped in a damp towel.', null, null),
  ('fresh-coriander', 'Fresh coriander', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 5, 'Refrigerate wrapped in a damp towel.', null, null),
  ('fresh-mint', 'Fresh mint', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 7, 'Refrigerate wrapped in a damp towel.', null, null),
  ('fresh-dill', 'Fresh dill', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 5, 'Refrigerate wrapped in a damp towel.', null, null),
  ('fresh-chives', 'Fresh chives', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 7, 'Refrigerate wrapped in a damp towel.', null, null),
  ('fresh-thyme', 'Fresh thyme', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 10, 'Refrigerate in a loosely closed bag.', null, null),
  ('fresh-rosemary', 'Fresh rosemary', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 14, 'Refrigerate in a loosely closed bag.', null, null),
  ('fresh-sage', 'Fresh sage', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 10, 'Refrigerate in a loosely closed bag.', null, null),
  ('fresh-oregano', 'Fresh oregano', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 7, 'Refrigerate in a loosely closed bag.', null, null),
  ('ginger', 'Ginger', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 21, 'Refrigerate unpeeled in a paper bag, or freeze whole.', null, 50),
  ('lemongrass', 'Lemongrass', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 14, 'Refrigerate wrapped, or freeze the trimmed stalks.', null, 20),
  ('spring-onion', 'Spring onion', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 10, 'Refrigerate upright with the roots in water.', null, 15),
  ('shallot', 'Shallot', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 30, 'Store in a cool, dry, ventilated place.', null, 30),
  ('red-chilli', 'Red chilli', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 14, 'Refrigerate dry in a ventilated bag, or freeze whole.', null, 10),
  ('green-chilli', 'Green chilli', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 14, 'Refrigerate dry in a ventilated bag, or freeze whole.', null, 10),
  ('jalapeno', 'Jalapeno', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 14, 'Refrigerate dry in a ventilated bag.', null, 15),
  ('kaffir-lime-leaves', 'Kaffir lime leaves', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 14, 'Refrigerate sealed, or freeze for months.', null, null),
  ('curry-leaves', 'Curry leaves', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 10, 'Refrigerate sealed, or freeze on the stem.', null, null),

  -- Oils and cooking fats.
  ('extra-virgin-olive-oil', 'Extra virgin olive oil', 'ml', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store sealed away from heat and light.', 0.91, null),
  ('sunflower-oil', 'Sunflower oil', 'ml', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store sealed away from heat and light.', 0.92, null),
  ('rapeseed-oil', 'Rapeseed oil', 'ml', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store sealed away from heat and light.', 0.92, null),
  ('vegetable-oil', 'Vegetable oil', 'ml', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store sealed away from heat and light.', 0.92, null),
  ('sesame-oil', 'Toasted sesame oil', 'ml', array['vegan', 'vegetarian'], array['sesame'], 'pantry', 365, 'Store sealed away from heat and light; refrigerate after opening.', 0.92, null),
  ('peanut-oil', 'Peanut oil', 'ml', array['vegan', 'vegetarian'], array['peanuts'], 'pantry', 365, 'Store sealed away from heat and light.', 0.91, null),
  ('coconut-oil', 'Coconut oil', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 540, 'Store sealed at room temperature; it solidifies when cool.', null, null),
  ('butter', 'Butter', 'g', array['vegetarian'], array['milk'], 'refrigerator', 30, 'Keep refrigerated and wrapped, or freeze portions.', null, null),
  ('unsalted-butter', 'Unsalted butter', 'g', array['vegetarian'], array['milk'], 'refrigerator', 21, 'Keep refrigerated and wrapped, or freeze portions.', null, null),
  ('ghee', 'Ghee', 'g', array['vegetarian'], array['milk'], 'pantry', 365, 'Store sealed at room temperature and use a dry spoon.', null, null),
  ('margarine', 'Margarine', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 60, 'Keep refrigerated and sealed.', null, null),
  ('lard', 'Lard', 'g', '{}', '{}', 'refrigerator', 180, 'Keep refrigerated and sealed.', null, null),

  -- Vinegars.
  ('white-vinegar', 'White vinegar', 'ml', array['vegan', 'vegetarian'], '{}', 'pantry', 1095, 'Store sealed at room temperature.', 1.01, null),
  ('white-wine-vinegar', 'White wine vinegar', 'ml', array['vegan', 'vegetarian'], array['sulphites'], 'pantry', 1095, 'Store sealed at room temperature.', 1.01, null),
  ('red-wine-vinegar', 'Red wine vinegar', 'ml', array['vegan', 'vegetarian'], array['sulphites'], 'pantry', 1095, 'Store sealed at room temperature.', 1.01, null),
  ('balsamic-vinegar', 'Balsamic vinegar', 'ml', array['vegan', 'vegetarian'], array['sulphites'], 'pantry', 1095, 'Store sealed at room temperature.', 1.06, null),
  ('rice-vinegar', 'Rice vinegar', 'ml', array['vegan', 'vegetarian'], '{}', 'pantry', 1095, 'Store sealed at room temperature.', 1.01, null),
  ('apple-cider-vinegar', 'Apple cider vinegar', 'ml', array['vegan', 'vegetarian'], array['sulphites'], 'pantry', 1095, 'Store sealed at room temperature.', 1.01, null),

  -- Sauces, pastes, and condiments.
  ('soy-sauce', 'Soy sauce', 'ml', array['vegan', 'vegetarian'], array['soybeans', 'gluten'], 'pantry', 730, 'Store sealed; refrigerate after opening for best flavour.', 1.15, null),
  ('tamari', 'Tamari', 'ml', array['vegan', 'vegetarian'], array['soybeans'], 'pantry', 730, 'Store sealed; refrigerate after opening for best flavour.', 1.15, null),
  ('fish-sauce', 'Fish sauce', 'ml', '{}', array['fish'], 'pantry', 730, 'Store sealed at room temperature.', 1.20, null),
  ('oyster-sauce', 'Oyster sauce', 'ml', '{}', array['molluscs', 'soybeans', 'gluten'], 'pantry', 365, 'Refrigerate after opening.', 1.25, null),
  ('mirin', 'Mirin', 'ml', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store sealed; refrigerate after opening.', 1.10, null),
  ('miso-paste', 'Miso paste', 'g', array['vegan', 'vegetarian'], array['soybeans'], 'refrigerator', 365, 'Keep refrigerated and sealed.', null, null),
  ('gochujang', 'Gochujang', 'g', array['vegan', 'vegetarian'], array['soybeans', 'gluten'], 'refrigerator', 365, 'Keep refrigerated after opening.', null, null),
  ('sriracha', 'Sriracha', 'ml', array['vegan', 'vegetarian'], '{}', 'pantry', 540, 'Store sealed; refrigerate after opening.', 1.15, null),
  ('hot-sauce', 'Hot sauce', 'ml', array['vegan', 'vegetarian'], '{}', 'pantry', 540, 'Store sealed; refrigerate after opening.', 1.02, null),
  ('harissa', 'Harissa paste', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 180, 'Refrigerate after opening and cover with a film of oil.', null, null),
  ('tahini', 'Tahini', 'g', array['vegan', 'vegetarian'], array['sesame'], 'pantry', 365, 'Store sealed; stir before use and refrigerate after opening.', null, null),
  ('mustard', 'Mustard', 'g', array['vegan', 'vegetarian'], array['mustard'], 'refrigerator', 365, 'Refrigerate after opening.', null, null),
  ('dijon-mustard', 'Dijon mustard', 'g', array['vegan', 'vegetarian'], array['mustard', 'sulphites'], 'refrigerator', 365, 'Refrigerate after opening.', null, null),
  ('mayonnaise', 'Mayonnaise', 'g', array['vegetarian'], array['eggs', 'mustard'], 'refrigerator', 60, 'Refrigerate after opening and use a clean spoon.', null, null),
  ('ketchup', 'Ketchup', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 180, 'Refrigerate after opening.', null, null),
  ('bbq-sauce', 'BBQ sauce', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 180, 'Refrigerate after opening.', null, null),
  ('worcestershire-sauce', 'Worcestershire sauce', 'ml', '{}', array['fish'], 'pantry', 730, 'Store sealed at room temperature.', 1.10, null),
  ('hoisin-sauce', 'Hoisin sauce', 'g', array['vegan', 'vegetarian'], array['soybeans', 'gluten', 'sesame'], 'refrigerator', 365, 'Refrigerate after opening.', null, null),
  ('sweet-chilli-sauce', 'Sweet chilli sauce', 'ml', array['vegan', 'vegetarian'], '{}', 'pantry', 540, 'Store sealed; refrigerate after opening.', 1.20, null),
  ('red-curry-paste', 'Red curry paste', 'g', '{}', array['crustaceans', 'fish'], 'refrigerator', 180, 'Refrigerate after opening, or freeze in portions.', null, null),
  ('green-curry-paste', 'Green curry paste', 'g', '{}', array['crustaceans', 'fish'], 'refrigerator', 180, 'Refrigerate after opening, or freeze in portions.', null, null),
  ('pesto', 'Basil pesto', 'g', array['vegetarian'], array['milk', 'nuts'], 'refrigerator', 14, 'Refrigerate after opening and cover with a film of oil.', null, null),
  ('white-wine', 'White wine', 'ml', array['vegan', 'vegetarian'], array['sulphites'], 'refrigerator', 5, 'Refrigerate once opened and use for cooking within days.', 0.99, null),
  ('red-wine', 'Red wine', 'ml', array['vegan', 'vegetarian'], array['sulphites'], 'pantry', 5, 'Reseal and use for cooking within days.', 0.99, null),
  ('lemon-juice', 'Lemon juice', 'ml', array['vegan', 'vegetarian'], '{}', 'refrigerator', 14, 'Keep refrigerated after opening.', 1.02, null),
  ('lime-juice', 'Lime juice', 'ml', array['vegan', 'vegetarian'], '{}', 'refrigerator', 14, 'Keep refrigerated after opening.', 1.02, null),
  ('orange-juice', 'Orange juice', 'ml', array['vegan', 'vegetarian'], '{}', 'refrigerator', 7, 'Keep refrigerated and shake before use.', 1.04, null),
  ('peanut-butter', 'Peanut butter', 'g', array['vegan', 'vegetarian'], array['peanuts'], 'pantry', 365, 'Store sealed; refrigerate natural varieties after opening.', null, null),
  ('jam', 'Fruit jam', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 60, 'Refrigerate after opening and use a clean spoon.', null, null),
  ('chocolate-spread', 'Chocolate spread', 'g', array['vegetarian'], array['nuts', 'milk', 'soybeans'], 'pantry', 180, 'Store sealed at room temperature.', null, null),

  -- Vegetables.
  ('cherry-tomato', 'Cherry tomato', 'g', array['vegan', 'vegetarian'], '{}', 'counter', 7, 'Keep at room temperature away from direct sunlight.', null, 15),
  ('red-onion', 'Red onion', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 30, 'Store in a cool, dry, ventilated place.', null, 110),
  ('sweet-potato', 'Sweet potato', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 21, 'Keep cool, dark, and dry; do not refrigerate.', null, 200),
  ('cauliflower', 'Cauliflower', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 7, 'Refrigerate unwashed in a loose bag.', null, 600),
  ('kale', 'Kale', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 7, 'Refrigerate dry with an absorbent towel.', null, null),
  ('lettuce', 'Lettuce', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 7, 'Refrigerate dry with an absorbent towel.', null, 300),
  ('rocket', 'Rocket', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 5, 'Refrigerate dry with an absorbent towel.', null, null),
  ('cabbage', 'White cabbage', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 30, 'Refrigerate whole and unwashed.', null, 900),
  ('red-cabbage', 'Red cabbage', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 30, 'Refrigerate whole and unwashed.', null, 900),
  ('chinese-cabbage', 'Chinese cabbage', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 14, 'Refrigerate wrapped in a ventilated bag.', null, 700),
  ('brussels-sprouts', 'Brussels sprouts', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 10, 'Refrigerate unwashed in a ventilated bag.', null, 20),
  ('courgette', 'Courgette', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 7, 'Refrigerate dry in a ventilated bag.', null, 200),
  ('aubergine', 'Aubergine', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 7, 'Refrigerate loosely wrapped; avoid the coldest shelf.', null, 250),
  ('red-bell-pepper', 'Red bell pepper', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 10, 'Refrigerate dry in a ventilated bag.', null, 150),
  ('green-bell-pepper', 'Green bell pepper', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 10, 'Refrigerate dry in a ventilated bag.', null, 150),
  ('yellow-bell-pepper', 'Yellow bell pepper', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 10, 'Refrigerate dry in a ventilated bag.', null, 150),
  ('cucumber', 'Cucumber', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 7, 'Refrigerate wrapped; avoid the coldest shelf.', null, 300),
  ('celery', 'Celery', 'g', array['vegan', 'vegetarian'], array['celery'], 'refrigerator', 14, 'Refrigerate wrapped in foil to keep the stalks crisp.', null, 40),
  ('leek', 'Leek', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 14, 'Refrigerate unwashed in a ventilated bag.', null, 200),
  ('green-beans', 'Green beans', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 7, 'Refrigerate dry in a ventilated bag.', null, null),
  ('peas', 'Fresh peas', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 5, 'Refrigerate in the pod and shell just before cooking.', null, null),
  ('corn-on-the-cob', 'Corn on the cob', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 5, 'Refrigerate in the husk and cook soon after buying.', null, 250),
  ('mushrooms', 'Button mushrooms', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 7, 'Refrigerate in a paper bag, never sealed plastic.', null, 20),
  ('portobello-mushrooms', 'Portobello mushrooms', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 7, 'Refrigerate in a paper bag, never sealed plastic.', null, 60),
  ('shiitake-mushrooms', 'Shiitake mushrooms', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 7, 'Refrigerate in a paper bag, never sealed plastic.', null, 15),
  ('asparagus', 'Asparagus', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 5, 'Stand the spears upright in a little water.', null, 20),
  ('beetroot', 'Beetroot', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 21, 'Trim the leaves and refrigerate the roots in a bag.', null, 150),
  ('radish', 'Radish', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 10, 'Trim the leaves and refrigerate in a sealed box.', null, 15),
  ('turnip', 'Turnip', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 21, 'Refrigerate dry in a ventilated bag.', null, 150),
  ('parsnip', 'Parsnip', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 21, 'Refrigerate dry in a ventilated bag.', null, 130),
  ('pumpkin', 'Pumpkin', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 60, 'Store whole in a cool, dry place; refrigerate once cut.', null, 1500),
  ('butternut-squash', 'Butternut squash', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 60, 'Store whole in a cool, dry place; refrigerate once cut.', null, 1000),
  ('fennel-bulb', 'Fennel bulb', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 10, 'Refrigerate in a ventilated bag.', null, 250),
  ('artichoke', 'Artichoke', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 7, 'Refrigerate sprinkled with a little water in a bag.', null, 300),
  ('bok-choy', 'Bok choy', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 7, 'Refrigerate unwashed in a ventilated bag.', null, 150),
  ('bean-sprouts', 'Bean sprouts', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 3, 'Keep refrigerated and use very quickly.', null, null),
  ('edamame', 'Edamame', 'g', array['vegan', 'vegetarian'], array['soybeans'], 'freezer', 365, 'Keep frozen until use.', null, null),
  ('okra', 'Okra', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 5, 'Refrigerate dry in a paper bag.', null, null),

  -- Fruit.
  ('lemon', 'Lemon', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 21, 'Refrigerate in a sealed bag to keep them juicy.', null, 100),
  ('lime', 'Lime', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 21, 'Refrigerate in a sealed bag to keep them juicy.', null, 65),
  ('orange', 'Orange', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 21, 'Refrigerate loose, or keep on the counter for a week.', null, 150),
  ('grapefruit', 'Grapefruit', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 21, 'Refrigerate loose in the crisper drawer.', null, 400),
  ('apple', 'Apple', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 30, 'Refrigerate away from other produce; apples speed ripening.', null, 180),
  ('pear', 'Pear', 'g', array['vegan', 'vegetarian'], '{}', 'counter', 7, 'Ripen on the counter, then refrigerate.', null, 180),
  ('banana', 'Banana', 'g', array['vegan', 'vegetarian'], '{}', 'counter', 7, 'Keep at room temperature away from other produce.', null, 120),
  ('strawberry', 'Strawberry', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 4, 'Refrigerate unwashed in a ventilated box.', null, 15),
  ('blueberry', 'Blueberry', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 10, 'Refrigerate unwashed in a ventilated box.', null, null),
  ('raspberry', 'Raspberry', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 3, 'Refrigerate unwashed in a single layer.', null, null),
  ('blackberry', 'Blackberry', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 4, 'Refrigerate unwashed in a single layer.', null, null),
  ('grapes', 'Grapes', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 10, 'Refrigerate unwashed on the stem.', null, null),
  ('pineapple', 'Pineapple', 'g', array['vegan', 'vegetarian'], '{}', 'counter', 5, 'Ripen on the counter, then refrigerate once cut.', null, 1200),
  ('mango', 'Mango', 'g', array['vegan', 'vegetarian'], '{}', 'counter', 7, 'Ripen on the counter, then refrigerate.', null, 300),
  ('avocado', 'Avocado', 'g', array['vegan', 'vegetarian'], '{}', 'counter', 5, 'Ripen on the counter, then refrigerate to hold it.', null, 200),
  ('kiwi', 'Kiwi', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 14, 'Refrigerate firm fruit; ripen on the counter as needed.', null, 75),
  ('peach', 'Peach', 'g', array['vegan', 'vegetarian'], '{}', 'counter', 5, 'Ripen on the counter, then refrigerate.', null, 150),
  ('plum', 'Plum', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 7, 'Ripen on the counter, then refrigerate.', null, 60),
  ('cherry', 'Cherry', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 7, 'Refrigerate unwashed with the stems on.', null, null),
  ('watermelon', 'Watermelon', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 14, 'Keep whole at room temperature; refrigerate once cut.', null, 5000),
  ('melon', 'Melon', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 10, 'Keep whole at room temperature; refrigerate once cut.', null, 1200),
  ('pomegranate', 'Pomegranate', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 21, 'Refrigerate whole in a ventilated bag.', null, 280),
  ('fig', 'Fig', 'g', array['vegan', 'vegetarian'], '{}', 'refrigerator', 5, 'Refrigerate in a single layer and use quickly.', null, 50),

  -- Meat and poultry.
  ('chicken-thigh', 'Chicken thigh', 'g', '{}', '{}', 'refrigerator', 2, 'Keep refrigerated and separate from ready-to-eat food.', null, 100),
  ('chicken-drumstick', 'Chicken drumstick', 'g', '{}', '{}', 'refrigerator', 2, 'Keep refrigerated and separate from ready-to-eat food.', null, 90),
  ('chicken-wings', 'Chicken wings', 'g', '{}', '{}', 'refrigerator', 2, 'Keep refrigerated and separate from ready-to-eat food.', null, 50),
  ('whole-chicken', 'Whole chicken', 'g', '{}', '{}', 'refrigerator', 2, 'Keep refrigerated on the bottom shelf in a sealed tray.', null, 1400),
  ('ground-beef', 'Ground beef', 'g', '{}', '{}', 'refrigerator', 2, 'Keep refrigerated and cook or freeze within two days.', null, null),
  ('beef-steak', 'Beef steak', 'g', '{}', '{}', 'refrigerator', 3, 'Keep refrigerated and separate from ready-to-eat food.', null, 250),
  ('beef-stewing', 'Stewing beef', 'g', '{}', '{}', 'refrigerator', 3, 'Keep refrigerated and separate from ready-to-eat food.', null, null),
  ('pork-chop', 'Pork chop', 'g', '{}', '{}', 'refrigerator', 3, 'Keep refrigerated and separate from ready-to-eat food.', null, 180),
  ('pork-belly', 'Pork belly', 'g', '{}', '{}', 'refrigerator', 3, 'Keep refrigerated and separate from ready-to-eat food.', null, null),
  ('pork-tenderloin', 'Pork tenderloin', 'g', '{}', '{}', 'refrigerator', 3, 'Keep refrigerated and separate from ready-to-eat food.', null, 450),
  ('ground-pork', 'Ground pork', 'g', '{}', '{}', 'refrigerator', 2, 'Keep refrigerated and cook or freeze within two days.', null, null),
  ('bacon', 'Bacon', 'g', '{}', '{}', 'refrigerator', 7, 'Keep refrigerated and sealed after opening.', null, 25),
  ('sausage', 'Sausage', 'g', '{}', array['sulphites'], 'refrigerator', 3, 'Keep refrigerated and separate from ready-to-eat food.', null, 60),
  ('chorizo', 'Chorizo', 'g', '{}', '{}', 'refrigerator', 30, 'Refrigerate wrapped; cured whole sausages keep longest.', null, 200),
  ('ham', 'Ham', 'g', '{}', '{}', 'refrigerator', 7, 'Keep refrigerated and sealed after opening.', null, 20),
  ('salami', 'Salami', 'g', '{}', '{}', 'refrigerator', 21, 'Refrigerate wrapped in paper rather than plastic.', null, 5),
  ('prosciutto', 'Prosciutto', 'g', '{}', '{}', 'refrigerator', 14, 'Refrigerate wrapped in paper rather than plastic.', null, 15),
  ('lamb-chop', 'Lamb chop', 'g', '{}', '{}', 'refrigerator', 3, 'Keep refrigerated and separate from ready-to-eat food.', null, 100),
  ('ground-lamb', 'Ground lamb', 'g', '{}', '{}', 'refrigerator', 2, 'Keep refrigerated and cook or freeze within two days.', null, null),
  ('lamb-shoulder', 'Lamb shoulder', 'g', '{}', '{}', 'refrigerator', 3, 'Keep refrigerated and separate from ready-to-eat food.', null, null),
  ('turkey-breast', 'Turkey breast', 'g', '{}', '{}', 'refrigerator', 2, 'Keep refrigerated and separate from ready-to-eat food.', null, 200),
  ('ground-turkey', 'Ground turkey', 'g', '{}', '{}', 'refrigerator', 2, 'Keep refrigerated and cook or freeze within two days.', null, null),
  ('duck-breast', 'Duck breast', 'g', '{}', '{}', 'refrigerator', 3, 'Keep refrigerated and separate from ready-to-eat food.', null, 300),

  -- Fish and seafood.
  ('cod', 'Cod', 'g', '{}', array['fish'], 'refrigerator', 2, 'Keep refrigerated on ice and use promptly.', null, 150),
  ('haddock', 'Haddock', 'g', '{}', array['fish'], 'refrigerator', 2, 'Keep refrigerated on ice and use promptly.', null, 150),
  ('sea-bass', 'Sea bass', 'g', '{}', array['fish'], 'refrigerator', 2, 'Keep refrigerated on ice and use promptly.', null, 130),
  ('mackerel', 'Mackerel', 'g', '{}', array['fish'], 'refrigerator', 2, 'Keep refrigerated on ice and use promptly.', null, 250),
  ('sardines', 'Sardines', 'g', '{}', array['fish'], 'refrigerator', 2, 'Keep refrigerated on ice and use promptly.', null, 80),
  ('tuna-steak', 'Tuna steak', 'g', '{}', array['fish'], 'refrigerator', 2, 'Keep refrigerated on ice and use promptly.', null, 180),
  ('canned-tuna', 'Canned tuna', 'g', '{}', array['fish'], 'pantry', 730, 'Store sealed in the pantry; refrigerate after opening.', null, null),
  ('anchovies', 'Anchovy fillets', 'g', '{}', array['fish'], 'pantry', 365, 'Store sealed in the pantry; refrigerate under oil after opening.', null, 4),
  ('smoked-salmon', 'Smoked salmon', 'g', '{}', array['fish'], 'refrigerator', 7, 'Keep refrigerated and sealed; use quickly once opened.', null, null),
  ('prawns', 'Prawns', 'g', '{}', array['crustaceans'], 'refrigerator', 2, 'Keep refrigerated on ice, or keep frozen until use.', null, 10),
  ('mussels', 'Mussels', 'g', '{}', array['molluscs'], 'refrigerator', 2, 'Refrigerate in an open bowl under a damp cloth.', null, 10),
  ('squid', 'Squid', 'g', '{}', array['molluscs'], 'refrigerator', 2, 'Keep refrigerated on ice and use promptly.', null, null),
  ('scallops', 'Scallops', 'g', '{}', array['molluscs'], 'refrigerator', 2, 'Keep refrigerated on ice and use promptly.', null, 20),
  ('crab-meat', 'Crab meat', 'g', '{}', array['crustaceans'], 'refrigerator', 2, 'Keep refrigerated and use promptly.', null, null),

  -- Meat-free proteins.
  ('silken-tofu', 'Silken tofu', 'g', array['vegan', 'vegetarian'], array['soybeans'], 'refrigerator', 7, 'Keep refrigerated and use promptly after opening.', null, 300),
  ('tempeh', 'Tempeh', 'g', array['vegan', 'vegetarian'], array['soybeans'], 'refrigerator', 10, 'Keep refrigerated and sealed, or freeze.', null, 200),
  ('seitan', 'Seitan', 'g', array['vegan', 'vegetarian'], array['gluten'], 'refrigerator', 10, 'Keep refrigerated and sealed.', null, null),
  ('halloumi', 'Halloumi', 'g', array['vegetarian'], array['milk'], 'refrigerator', 30, 'Keep refrigerated in its brine until use.', null, 225),
  ('paneer', 'Paneer', 'g', array['vegetarian'], array['milk'], 'refrigerator', 14, 'Keep refrigerated and sealed.', null, 200),

  -- Dairy and plant alternatives.
  ('whole-milk', 'Whole milk', 'ml', array['vegetarian'], array['milk'], 'refrigerator', 7, 'Keep refrigerated and follow the package date.', 1.03, null),
  ('semi-skimmed-milk', 'Semi-skimmed milk', 'ml', array['vegetarian'], array['milk'], 'refrigerator', 7, 'Keep refrigerated and follow the package date.', 1.03, null),
  ('skimmed-milk', 'Skimmed milk', 'ml', array['vegetarian'], array['milk'], 'refrigerator', 7, 'Keep refrigerated and follow the package date.', 1.03, null),
  ('buttermilk', 'Buttermilk', 'ml', array['vegetarian'], array['milk'], 'refrigerator', 10, 'Keep refrigerated and shake before use.', 1.03, null),
  ('double-cream', 'Double cream', 'ml', array['vegetarian'], array['milk'], 'refrigerator', 7, 'Keep refrigerated and sealed.', 1.00, null),
  ('cooking-cream', 'Cooking cream', 'ml', array['vegetarian'], array['milk'], 'refrigerator', 10, 'Keep refrigerated and sealed.', 1.00, null),
  ('creme-fraiche', 'Creme fraiche', 'g', array['vegetarian'], array['milk'], 'refrigerator', 14, 'Keep refrigerated and use a clean spoon.', null, null),
  ('sour-cream', 'Sour cream', 'g', array['vegetarian'], array['milk'], 'refrigerator', 14, 'Keep refrigerated and use a clean spoon.', null, null),
  ('greek-yogurt', 'Greek yogurt', 'g', array['vegetarian'], array['milk'], 'refrigerator', 14, 'Keep refrigerated and sealed.', null, null),
  ('parmesan', 'Parmesan', 'g', array['vegetarian'], array['milk'], 'refrigerator', 60, 'Refrigerate wrapped in paper, then loosely in foil.', null, null),
  ('mozzarella', 'Mozzarella', 'g', array['vegetarian'], array['milk'], 'refrigerator', 14, 'Keep refrigerated in its liquid until use.', null, 125),
  ('cheddar', 'Cheddar', 'g', array['vegetarian'], array['milk'], 'refrigerator', 30, 'Refrigerate wrapped; rewrap after each use.', null, null),
  ('feta', 'Feta', 'g', array['vegetarian'], array['milk'], 'refrigerator', 30, 'Keep refrigerated in its brine.', null, null),
  ('gouda', 'Gouda', 'g', array['vegetarian'], array['milk'], 'refrigerator', 30, 'Refrigerate wrapped; rewrap after each use.', null, null),
  ('ricotta', 'Ricotta', 'g', array['vegetarian'], array['milk'], 'refrigerator', 7, 'Keep refrigerated and use promptly after opening.', null, null),
  ('cream-cheese', 'Cream cheese', 'g', array['vegetarian'], array['milk'], 'refrigerator', 14, 'Keep refrigerated and use a clean knife.', null, null),
  ('blue-cheese', 'Blue cheese', 'g', array['vegetarian'], array['milk'], 'refrigerator', 21, 'Refrigerate wrapped in paper, away from other food.', null, null),
  ('goat-cheese', 'Goat cheese', 'g', array['vegetarian'], array['milk'], 'refrigerator', 14, 'Refrigerate wrapped and sealed.', null, null),
  ('mascarpone', 'Mascarpone', 'g', array['vegetarian'], array['milk'], 'refrigerator', 10, 'Keep refrigerated and use promptly after opening.', null, null),
  ('oat-milk', 'Oat milk', 'ml', array['vegan', 'vegetarian'], array['gluten'], 'refrigerator', 7, 'Refrigerate after opening and shake before use.', 1.03, null),
  ('soy-milk', 'Soy milk', 'ml', array['vegan', 'vegetarian'], array['soybeans'], 'refrigerator', 7, 'Refrigerate after opening and shake before use.', 1.03, null),
  ('almond-milk', 'Almond milk', 'ml', array['vegan', 'vegetarian'], array['nuts'], 'refrigerator', 7, 'Refrigerate after opening and shake before use.', 1.02, null),
  ('coconut-milk', 'Coconut milk', 'ml', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Store sealed in the pantry; refrigerate after opening.', 0.98, null),
  ('coconut-cream', 'Coconut cream', 'ml', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Store sealed in the pantry; refrigerate after opening.', 0.98, null),

  -- Rice, grains, and pulses.
  ('basmati-rice', 'Basmati rice', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('jasmine-rice', 'Jasmine rice', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('arborio-rice', 'Arborio rice', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('brown-rice', 'Brown rice', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 180, 'Store dry and sealed; the bran oil turns rancid in time.', null, null),
  ('sushi-rice', 'Sushi rice', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('couscous', 'Couscous', 'g', array['vegan', 'vegetarian'], array['gluten'], 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('bulgur', 'Bulgur wheat', 'g', array['vegan', 'vegetarian'], array['gluten'], 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('quinoa', 'Quinoa', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('pearl-barley', 'Pearl barley', 'g', array['vegan', 'vegetarian'], array['gluten'], 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('oats', 'Rolled oats', 'g', array['vegan', 'vegetarian'], array['gluten'], 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('buckwheat', 'Buckwheat', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('black-beans', 'Dried black beans', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Store dry in a sealed container.', null, null),
  ('kidney-beans', 'Dried kidney beans', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Store dry in a sealed container.', null, null),
  ('white-beans', 'Dried white beans', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Store dry in a sealed container.', null, null),
  ('split-peas', 'Split peas', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Store dry in a sealed container.', null, null),

  -- Pasta, noodles, bread, and pastry.
  ('spaghetti', 'Spaghetti', 'g', array['vegan', 'vegetarian'], array['gluten'], 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('penne', 'Penne', 'g', array['vegan', 'vegetarian'], array['gluten'], 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('fusilli', 'Fusilli', 'g', array['vegan', 'vegetarian'], array['gluten'], 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('tagliatelle', 'Tagliatelle', 'g', array['vegetarian'], array['gluten', 'eggs'], 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('lasagne-sheets', 'Lasagne sheets', 'g', array['vegan', 'vegetarian'], array['gluten'], 'pantry', 365, 'Store dry and flat in a sealed container.', null, 12),
  ('macaroni', 'Macaroni', 'g', array['vegan', 'vegetarian'], array['gluten'], 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('orzo', 'Orzo', 'g', array['vegan', 'vegetarian'], array['gluten'], 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('gnocchi', 'Gnocchi', 'g', array['vegetarian'], array['gluten'], 'refrigerator', 21, 'Keep refrigerated and sealed until use.', null, null),
  ('rice-noodles', 'Rice noodles', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 540, 'Store dry in a sealed container.', null, null),
  ('udon-noodles', 'Udon noodles', 'g', array['vegan', 'vegetarian'], array['gluten'], 'pantry', 180, 'Store sealed; refrigerate fresh packs.', null, null),
  ('egg-noodles', 'Egg noodles', 'g', array['vegetarian'], array['gluten', 'eggs'], 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('soba-noodles', 'Soba noodles', 'g', array['vegan', 'vegetarian'], array['gluten'], 'pantry', 365, 'Store dry in a sealed container.', null, null),
  ('ramen-noodles', 'Ramen noodles', 'g', array['vegan', 'vegetarian'], array['gluten'], 'pantry', 180, 'Store sealed; refrigerate fresh packs.', null, null),
  ('baguette', 'Baguette', 'g', array['vegan', 'vegetarian'], array['gluten'], 'counter', 2, 'Keep in a paper bag and eat the same day, or freeze.', null, 250),
  ('sourdough-bread', 'Sourdough bread', 'g', array['vegan', 'vegetarian'], array['gluten'], 'counter', 5, 'Keep cut side down in a bread box or cloth bag.', null, 45),
  ('whole-wheat-bread', 'Whole wheat bread', 'g', array['vegan', 'vegetarian'], array['gluten'], 'counter', 5, 'Keep sealed or freeze portions.', null, 40),
  ('pita-bread', 'Pita bread', 'g', array['vegan', 'vegetarian'], array['gluten'], 'counter', 7, 'Keep sealed at room temperature, or freeze.', null, 60),
  ('naan', 'Naan', 'g', array['vegetarian'], array['gluten', 'milk'], 'counter', 7, 'Keep sealed at room temperature, or freeze.', null, 90),
  ('tortilla-wrap', 'Tortilla wrap', 'g', array['vegan', 'vegetarian'], array['gluten'], 'pantry', 30, 'Keep sealed; refrigerate after opening.', null, 60),
  ('corn-tortilla', 'Corn tortilla', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 30, 'Keep sealed; refrigerate after opening.', null, 30),
  ('burger-bun', 'Burger bun', 'g', array['vegetarian'], array['gluten'], 'counter', 5, 'Keep sealed at room temperature, or freeze.', null, 60),
  ('puff-pastry', 'Puff pastry', 'g', array['vegetarian'], array['gluten', 'milk'], 'refrigerator', 14, 'Keep refrigerated, or keep frozen until the day of use.', null, null),
  ('filo-pastry', 'Filo pastry', 'g', array['vegan', 'vegetarian'], array['gluten'], 'refrigerator', 14, 'Keep refrigerated and covered so the sheets stay pliable.', null, null),
  ('pizza-dough', 'Pizza dough', 'g', array['vegan', 'vegetarian'], array['gluten'], 'refrigerator', 7, 'Keep refrigerated and let it come to room temperature before shaping.', null, 250),

  -- Canned, jarred, and stock.
  ('canned-chopped-tomatoes', 'Canned chopped tomatoes', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Store sealed in the pantry; refrigerate after opening.', null, null),
  ('canned-peeled-tomatoes', 'Canned peeled tomatoes', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Store sealed in the pantry; refrigerate after opening.', null, null),
  ('passata', 'Passata', 'ml', array['vegan', 'vegetarian'], '{}', 'pantry', 540, 'Store sealed in the pantry; refrigerate after opening.', 1.05, null),
  ('tomato-paste', 'Tomato paste', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Refrigerate after opening and cover with a film of oil.', null, null),
  ('sun-dried-tomatoes', 'Sun-dried tomatoes', 'g', array['vegan', 'vegetarian'], array['sulphites'], 'pantry', 365, 'Store sealed; refrigerate jars in oil after opening.', null, null),
  ('vegetable-stock', 'Vegetable stock', 'ml', array['vegan', 'vegetarian'], array['celery'], 'pantry', 365, 'Store sealed in the pantry; refrigerate after opening.', 1.00, null),
  ('chicken-stock', 'Chicken stock', 'ml', '{}', array['celery'], 'pantry', 365, 'Store sealed in the pantry; refrigerate after opening.', 1.00, null),
  ('beef-stock', 'Beef stock', 'ml', '{}', array['celery'], 'pantry', 365, 'Store sealed in the pantry; refrigerate after opening.', 1.00, null),
  ('stock-cube', 'Stock cube', 'each', '{}', array['celery'], 'pantry', 540, 'Store dry in a sealed container.', null, 10),
  ('canned-black-beans', 'Canned black beans', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Store sealed in the pantry; refrigerate after opening.', null, null),
  ('canned-kidney-beans', 'Canned kidney beans', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Store sealed in the pantry; refrigerate after opening.', null, null),
  ('canned-white-beans', 'Canned white beans', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Store sealed in the pantry; refrigerate after opening.', null, null),
  ('canned-sweetcorn', 'Canned sweetcorn', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 730, 'Store sealed in the pantry; refrigerate after opening.', null, null),
  ('green-olives', 'Green olives', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store sealed; refrigerate in the brine after opening.', null, 4),
  ('black-olives', 'Black olives', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store sealed; refrigerate in the brine after opening.', null, 4),
  ('capers', 'Capers', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store sealed; refrigerate in the brine after opening.', null, 1),
  ('gherkins', 'Gherkins', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store sealed; refrigerate after opening.', null, 25),
  ('pickled-jalapenos', 'Pickled jalapenos', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store sealed; refrigerate after opening.', null, null),
  ('artichoke-hearts', 'Artichoke hearts', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store sealed; refrigerate after opening.', null, 30),
  ('roasted-red-peppers', 'Roasted red peppers', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store sealed; refrigerate after opening.', null, null),

  -- Nuts, seeds, and dried fruit.
  ('almonds', 'Almonds', 'g', array['vegan', 'vegetarian'], array['nuts'], 'pantry', 365, 'Store sealed and cool; refrigerate for longer life.', null, null),
  ('walnuts', 'Walnuts', 'g', array['vegan', 'vegetarian'], array['nuts'], 'pantry', 180, 'Store sealed and cool; refrigerate for longer life.', null, null),
  ('cashews', 'Cashews', 'g', array['vegan', 'vegetarian'], array['nuts'], 'pantry', 365, 'Store sealed and cool; refrigerate for longer life.', null, null),
  ('pistachios', 'Pistachios', 'g', array['vegan', 'vegetarian'], array['nuts'], 'pantry', 365, 'Store sealed and cool; refrigerate for longer life.', null, null),
  ('hazelnuts', 'Hazelnuts', 'g', array['vegan', 'vegetarian'], array['nuts'], 'pantry', 365, 'Store sealed and cool; refrigerate for longer life.', null, null),
  ('pecans', 'Pecans', 'g', array['vegan', 'vegetarian'], array['nuts'], 'pantry', 180, 'Store sealed and cool; refrigerate for longer life.', null, null),
  ('pine-nuts', 'Pine nuts', 'g', array['vegan', 'vegetarian'], array['nuts'], 'refrigerator', 180, 'Refrigerate sealed; they turn rancid quickly.', null, null),
  ('peanuts', 'Peanuts', 'g', array['vegan', 'vegetarian'], array['peanuts'], 'pantry', 365, 'Store sealed and cool.', null, null),
  ('sesame-seeds', 'Sesame seeds', 'g', array['vegan', 'vegetarian'], array['sesame'], 'pantry', 365, 'Store sealed and cool.', null, null),
  ('sunflower-seeds', 'Sunflower seeds', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store sealed and cool.', null, null),
  ('pumpkin-seeds', 'Pumpkin seeds', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store sealed and cool.', null, null),
  ('chia-seeds', 'Chia seeds', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 540, 'Store dry in a sealed container.', null, null),
  ('flaxseed', 'Flaxseed', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store sealed and cool; refrigerate once ground.', null, null),
  ('poppy-seeds', 'Poppy seeds', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store sealed and cool.', null, null),
  ('raisins', 'Raisins', 'g', array['vegan', 'vegetarian'], array['sulphites'], 'pantry', 365, 'Store sealed in a cool, dry place.', null, null),
  ('dates', 'Dates', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store sealed in a cool, dry place; refrigerate to keep them soft.', null, 8),
  ('dried-apricots', 'Dried apricots', 'g', array['vegan', 'vegetarian'], array['sulphites'], 'pantry', 365, 'Store sealed in a cool, dry place.', null, 8),
  ('dried-cranberries', 'Dried cranberries', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store sealed in a cool, dry place.', null, null),
  ('prunes', 'Prunes', 'g', array['vegan', 'vegetarian'], array['sulphites'], 'pantry', 365, 'Store sealed in a cool, dry place.', null, 10),
  ('desiccated-coconut', 'Desiccated coconut', 'g', array['vegan', 'vegetarian'], '{}', 'pantry', 365, 'Store dry in a sealed container.', null, null),

  -- Freezer staples.
  ('frozen-peas', 'Frozen peas', 'g', array['vegan', 'vegetarian'], '{}', 'freezer', 365, 'Keep frozen until use and reseal the bag.', null, null),
  ('frozen-spinach', 'Frozen spinach', 'g', array['vegan', 'vegetarian'], '{}', 'freezer', 365, 'Keep frozen until use and reseal the bag.', null, null),
  ('frozen-mixed-vegetables', 'Frozen mixed vegetables', 'g', array['vegan', 'vegetarian'], '{}', 'freezer', 365, 'Keep frozen until use and reseal the bag.', null, null),
  ('frozen-berries', 'Frozen berries', 'g', array['vegan', 'vegetarian'], '{}', 'freezer', 365, 'Keep frozen until use and reseal the bag.', null, null),
  ('frozen-fries', 'Frozen fries', 'g', array['vegan', 'vegetarian'], '{}', 'freezer', 365, 'Keep frozen until use and reseal the bag.', null, null)
on conflict (slug) do update set
  name = excluded.name,
  dietary_tags = excluded.dietary_tags,
  allergens = excluded.allergens,
  recommended_storage_location = excluded.recommended_storage_location,
  typical_shelf_life_days = excluded.typical_shelf_life_days,
  storage_instructions = excluded.storage_instructions,
  density_g_per_ml = excluded.density_g_per_ml,
  average_unit_weight_g = excluded.average_unit_weight_g;
